name: Release Working Branch Lerna

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Ensure lerna can do the proper version bump
          # https://github.com/lerna/lerna/issues/2542
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Gatsby build
        uses: actions/cache@v2
        with:
          path: |
            demo/public
            demo/.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Configure NPM
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc

      - name: Lerna Publish
        run: yarn release --canary minor
